// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"\n\n**Characters:**\n":        115,
	"\n**Left the outfit:**":       34,
	"\n**Other characters:**":      86,
	"\n**Welcome to the outfit:**": 33,
	"\nStatus: _":                  120,
	"# PlanetSide 2 Spy\n\nSimple discord bot for PlanetSide 2 outfits\n\n## Links\n\n- [GitHub](https://github.com/x0k/ps2-spy)\n\t\t\n": 42,
	"%dh ":                                127,
	"%dm":                                 126,
	"%d・online":                           82,
	"%s (%s) is now offline (%s)":         28,
	"%s (%s) is now online (%s)":          26,
	"%s - %d":                             91,
	"%s - %s (Ends %s)":                   94,
	"%s - No alerts":                      96,
	"%s [%s] captured %s (%s) on %s (%s)": 40,
	"%s [%s] lost %s (%s) on %s (%s)":     41,
	"%s alerts":                           97,
	") by `":                              119,
	"Add new task":                        101,
	"Cancel":                              108,
	"Character":                           19,
	"Character notifications: off":        5,
	"Character notifications: on":         4,
	"Characters online:":                  84,
	"Default timezone":                    0,
	"Duration":                            24,
	"Duration too long: expected max %s got %s": 110,
	"Duration: %s": 106,
	"ENG":          13,
	"Enter the character names separated by comma": 79,
	"Enter the outfit tags separated by comma":     77,
	"Faction":                                              17,
	"Failed to extract field value":                        71,
	"Failed to load %s channel":                            70,
	"Failed to load %s population with %s":                 45,
	"Failed to load %s territory control":                  46,
	"Failed to load character names for %v (%s)":           69,
	"Failed to load character: %s":                         35,
	"Failed to load characters %v (%s)":                    52,
	"Failed to load characters: %v (%s)":                   30,
	"Failed to load facility: %s":                          36,
	"Failed to load global alerts from %s":                 48,
	"Failed to load global population with %s":             44,
	"Failed to load online members for %s channel (%s)":    49,
	"Failed to load outfit tags for %v (%s)":               68,
	"Failed to load outfit: %s (%s)":                       29,
	"Failed to load outfits %v (%s)":                       50,
	"Failed to load outfits by tags %v (%s)":               51,
	"Failed to load stats tracker task":                    64,
	"Failed to load stats tracker tasks":                   63,
	"Failed to load tracking settings for %s channel (%s)": 67,
	"Failed to load world alerts for %s from %s":           47,
	"Failed to parse language %q":                          80,
	"Failed to remove stats tracker task":                  65,
	"Failed to save field value for %s channel":            72,
	"Failed to save tracking settings for %s channel (%s)": 53,
	"Failed to start stats tracker":                        58,
	"Failed to stop stats tracker":                         60,
	"Friday":                                               132,
	"HA":                                                   14,
	"HS":                                                   21,
	"INF":                                                  10,
	"Invalid population type: %s":                          43,
	"Invalid stats tracker subcommand: %s":                 57,
	"KD":                                                   22,
	"Kills":                                                20,
	"LA":                                                   11,
	"Language":                                             1,
	"Language for this channel has been set to %q":         81,
	"Language: english":                                    2,
	"Language: russian":                                    3,
	"Loadout":                                              23,
	"Locked ":                                              118,
	"MAX":                                                  15,
	"MED":                                                  12,
	"Max amount of tasks per channel is %d":                109,
	"Monday":                                               128,
	"NC":                                                   88,
	"Next":                                                 103,
	"No":                                                   125,
	"No alerts":                                            98,
	"No characters":                                        116,
	"No characters online":                                 83,
	"No data collected":                                    39,
	"No outfits":                                           114,
	"Notes:\n- The time is specified in the time zone %q. This can be changed in the channel settings;\n- The maximum amount of tasks per channel is %d;\n- You can edit a task by clicking on it;\n- The “Remove” button deletes immediately without confirmation.\n": 99,
	"Nothing to track, please set tracking settings first": 56,
	"Outfit":                    18,
	"Outfit notifications: off": 7,
	"Outfit notifications: on":  6,
	"Period":                    93,
	"Platform: %s, started at: %s, stopped: %s, duration: %s\n```": 38,
	"Previous": 102,
	"Remove":   100,
	"Saturday": 133,
	"Settings are saved, but failed to load character names %v (%s)": 55,
	"Settings are saved, but failed to load outfit tags %v (%s)":     54,
	"Settings are updated.\n\n**Outfits:**\n":                        113,
	"Source: %s":                             90,
	"Stable":                                 121,
	"Starting hour: %d":                      104,
	"Starting minute: %d":                    105,
	"Stats tracker started":                  37,
	"Stats tracker task state not found":     66,
	"Stats tracker will be started soon":     61,
	"Stats tracker will be stopped soon":     62,
	"Submit":                                 107,
	"Sunday":                                 134,
	"TR":                                     87,
	"Territory Control":                      95,
	"There is no stats tracker to stop":      59,
	"Thursday":                               131,
	"Title updates: off":                     9,
	"Title updates: on":                      8,
	"Total population - %d":                  92,
	"Tracking Settings (PC)":                 73,
	"Tracking Settings (PS4 EU)":             74,
	"Tracking Settings (PS4 US)":             75,
	"Tuesday":                                129,
	"Unknown":                                16,
	"Unlocked ":                              117,
	"Unstable":                               122,
	"Update of ":                             31,
	"VS":                                     89,
	"Wednesday":                              130,
	"Which characters do you want to track?": 78,
	"Which outfits do you want to track?":    76,
	"Yes":                                    124,
	"Your task (%s, %s, %s) overlaps with existing task (%s, %s, %s)": 111,
	"[%s] %s (%s) is now offline (%s)":                                27,
	"[%s] %s (%s) is now online (%s)":                                 25,
	"] outfit (":                                                      85,
	"] outfit members:":                                               32,
	"_\nAlerts: _":                                                    123,
	"something went wrong":                                            112,
}

var enIndex = []uint32{ // 136 elements
	// Entry 0 - 1F
	0x00000000, 0x00000011, 0x0000001a, 0x0000002c,
	0x0000003e, 0x0000005a, 0x00000077, 0x00000090,
	0x000000aa, 0x000000bc, 0x000000cf, 0x000000d3,
	0x000000d6, 0x000000da, 0x000000de, 0x000000e1,
	0x000000e5, 0x000000ed, 0x000000f5, 0x000000fc,
	0x00000106, 0x0000010c, 0x0000010f, 0x00000112,
	0x0000011a, 0x00000123, 0x0000014f, 0x00000173,
	0x000001a0, 0x000001c5, 0x000001ea, 0x00000213,
	// Entry 20 - 3F
	0x00000222, 0x00000234, 0x00000254, 0x0000026e,
	0x0000028e, 0x000002ad, 0x000002c3, 0x0000030b,
	0x0000031d, 0x00000353, 0x00000385, 0x00000403,
	0x00000422, 0x0000044e, 0x00000479, 0x000004a0,
	0x000004d1, 0x000004f9, 0x00000531, 0x00000556,
	0x00000583, 0x000005ab, 0x000005e6, 0x00000627,
	0x0000066c, 0x000006a1, 0x000006c9, 0x000006e7,
	0x00000709, 0x00000726, 0x00000749, 0x0000076c,
	// Entry 40 - 5F
	0x0000078f, 0x000007b1, 0x000007d5, 0x000007f8,
	0x00000833, 0x00000860, 0x00000891, 0x000008ae,
	0x000008cc, 0x000008f9, 0x00000910, 0x0000092b,
	0x00000946, 0x0000096a, 0x00000993, 0x000009ba,
	0x000009e7, 0x00000a06, 0x00000a36, 0x00000a45,
	0x00000a5a, 0x00000a6d, 0x00000a78, 0x00000a93,
	0x00000a96, 0x00000a99, 0x00000a9c, 0x00000aaa,
	0x00000ab8, 0x00000ad1, 0x00000ad8, 0x00000af3,
	// Entry 60 - 7F
	0x00000b05, 0x00000b17, 0x00000b24, 0x00000b2e,
	0x00000c39, 0x00000c40, 0x00000c4d, 0x00000c56,
	0x00000c5b, 0x00000c70, 0x00000c87, 0x00000c97,
	0x00000c9e, 0x00000ca5, 0x00000cce, 0x00000cfe,
	0x00000d50, 0x00000d65, 0x00000d8e, 0x00000d99,
	0x00000db0, 0x00000dbe, 0x00000dcc, 0x00000dd8,
	0x00000ddf, 0x00000dee, 0x00000df5, 0x00000dfe,
	0x00000e0a, 0x00000e0e, 0x00000e11, 0x00000e18,
	// Entry 80 - 9F
	0x00000e24, 0x00000e2b, 0x00000e33, 0x00000e3d,
	0x00000e46, 0x00000e4d, 0x00000e56, 0x00000e5d,
} // Size: 568 bytes

const enData string = "" + // Size: 3677 bytes
	"\x02Default timezone\x02Language\x02Language: english\x02Language: russi" +
	"an\x02Character notifications: on\x02Character notifications: off\x02Out" +
	"fit notifications: on\x02Outfit notifications: off\x02Title updates: on" +
	"\x02Title updates: off\x02INF\x02LA\x02MED\x02ENG\x02HA\x02MAX\x02Unknow" +
	"n\x02Faction\x02Outfit\x02Character\x02Kills\x02HS\x02KD\x02Loadout\x02D" +
	"uration\x02[%[1]s] %[2]s (%[3]s) is now online (%[4]s)\x02%[1]s (%[2]s) " +
	"is now online (%[3]s)\x02[%[1]s] %[2]s (%[3]s) is now offline (%[4]s)" +
	"\x02%[1]s (%[2]s) is now offline (%[3]s)\x02Failed to load outfit: %[1]s" +
	" (%[2]s)\x02Failed to load characters: %[1]v (%[2]s)\x04\x00\x01 \x0a" +
	"\x02Update of\x02] outfit members:\x04\x01\x0a\x00\x1b\x02**Welcome to t" +
	"he outfit:**\x04\x01\x0a\x00\x15\x02**Left the outfit:**\x02Failed to lo" +
	"ad character: %[1]s\x02Failed to load facility: %[1]s\x02Stats tracker s" +
	"tarted\x02Platform: %[1]s, started at: %[2]s, stopped: %[3]s, duration: " +
	"%[4]s\x0a```\x02No data collected\x02%[1]s [%[2]s] captured %[3]s (%[4]s" +
	") on %[5]s (%[6]s)\x02%[1]s [%[2]s] lost %[3]s (%[4]s) on %[5]s (%[6]s)" +
	"\x04\x00\x04\x0a\x09\x09\x0av\x02# PlanetSide 2 Spy\x0a\x0aSimple discor" +
	"d bot for PlanetSide 2 outfits\x0a\x0a## Links\x0a\x0a- [GitHub](https:/" +
	"/github.com/x0k/ps2-spy)\x02Invalid population type: %[1]s\x02Failed to " +
	"load global population with %[1]s\x02Failed to load %[1]s population wit" +
	"h %[2]s\x02Failed to load %[1]s territory control\x02Failed to load worl" +
	"d alerts for %[1]s from %[2]s\x02Failed to load global alerts from %[1]s" +
	"\x02Failed to load online members for %[1]s channel (%[2]s)\x02Failed to" +
	" load outfits %[1]v (%[2]s)\x02Failed to load outfits by tags %[1]v (%[2" +
	"]s)\x02Failed to load characters %[1]v (%[2]s)\x02Failed to save trackin" +
	"g settings for %[1]s channel (%[2]s)\x02Settings are saved, but failed t" +
	"o load outfit tags %[1]v (%[2]s)\x02Settings are saved, but failed to lo" +
	"ad character names %[1]v (%[2]s)\x02Nothing to track, please set trackin" +
	"g settings first\x02Invalid stats tracker subcommand: %[1]s\x02Failed to" +
	" start stats tracker\x02There is no stats tracker to stop\x02Failed to s" +
	"top stats tracker\x02Stats tracker will be started soon\x02Stats tracker" +
	" will be stopped soon\x02Failed to load stats tracker tasks\x02Failed to" +
	" load stats tracker task\x02Failed to remove stats tracker task\x02Stats" +
	" tracker task state not found\x02Failed to load tracking settings for %[" +
	"1]s channel (%[2]s)\x02Failed to load outfit tags for %[1]v (%[2]s)\x02F" +
	"ailed to load character names for %[1]v (%[2]s)\x02Failed to load %[1]s " +
	"channel\x02Failed to extract field value\x02Failed to save field value f" +
	"or %[1]s channel\x02Tracking Settings (PC)\x02Tracking Settings (PS4 EU)" +
	"\x02Tracking Settings (PS4 US)\x02Which outfits do you want to track?" +
	"\x02Enter the outfit tags separated by comma\x02Which characters do you " +
	"want to track?\x02Enter the character names separated by comma\x02Failed" +
	" to parse language %[1]q\x02Language for this channel has been set to %[" +
	"1]q\x02%[1]d・online\x02No characters online\x02Characters online:\x02] o" +
	"utfit (\x04\x01\x0a\x00\x16\x02**Other characters:**\x02TR\x02NC\x02VS" +
	"\x02Source: %[1]s\x02%[1]s - %[2]d\x02Total population - %[1]d\x02Period" +
	"\x02%[1]s - %[2]s (Ends %[3]s)\x02Territory Control\x02%[1]s - No alerts" +
	"\x02%[1]s alerts\x02No alerts\x04\x00\x01\x0a\x85\x02\x02Notes:\x0a- The" +
	" time is specified in the time zone %[1]q. This can be changed in the ch" +
	"annel settings;\x0a- The maximum amount of tasks per channel is %[2]d;" +
	"\x0a- You can edit a task by clicking on it;\x0a- The “Remove” button de" +
	"letes immediately without confirmation.\x02Remove\x02Add new task\x02Pre" +
	"vious\x02Next\x02Starting hour: %[1]d\x02Starting minute: %[1]d\x02Durat" +
	"ion: %[1]s\x02Submit\x02Cancel\x02Max amount of tasks per channel is %[1" +
	"]d\x02Duration too long: expected max %[1]s got %[2]s\x02Your task (%[1]" +
	"s, %[2]s, %[3]s) overlaps with existing task (%[4]s, %[5]s, %[6]s)\x02so" +
	"mething went wrong\x04\x00\x01\x0a$\x02Settings are updated.\x0a\x0a**Ou" +
	"tfits:**\x02No outfits\x04\x02\x0a\x0a\x01\x0a\x10\x02**Characters:**" +
	"\x02No characters\x04\x00\x01 \x09\x02Unlocked\x04\x00\x01 \x07\x02Locke" +
	"d\x02) by `\x04\x01\x0a\x00\x0a\x02Status: _\x02Stable\x02Unstable\x02_" +
	"\x0aAlerts: _\x02Yes\x02No\x02%[1]dm\x04\x00\x01 \x07\x02%[1]dh\x02Monda" +
	"y\x02Tuesday\x02Wednesday\x02Thursday\x02Friday\x02Saturday\x02Sunday"

var ruIndex = []uint32{ // 136 elements
	// Entry 0 - 1F
	0x00000000, 0x00000034, 0x0000003d, 0x0000005c,
	0x00000075, 0x000000aa, 0x000000e1, 0x00000112,
	0x00000145, 0x00000176, 0x000001a9, 0x000001b0,
	0x000001b9, 0x000001c0, 0x000001c7, 0x000001d2,
	0x000001db, 0x000001f0, 0x000001ff, 0x0000020c,
	0x0000021d, 0x0000022e, 0x00000231, 0x00000236,
	0x00000241, 0x0000024c, 0x00000279, 0x0000029e,
	0x000002cd, 0x000002f4, 0x00000330, 0x00000374,
	// Entry 20 - 3F
	0x0000038e, 0x000003ab, 0x000003e5, 0x0000040d,
	0x00000445, 0x00000479, 0x000004aa, 0x00000527,
	0x0000053b, 0x00000579, 0x000005b5, 0x0000064a,
	0x0000067e, 0x000006ce, 0x0000070d, 0x0000075e,
	0x0000079e, 0x000007e6, 0x00000843, 0x00000880,
	0x000008cd, 0x00000910, 0x00000976, 0x000009f3,
	0x00000a78, 0x00000af8, 0x00000b4d, 0x00000ba2,
	0x00000be6, 0x00000c3d, 0x00000c8b, 0x00000cdb,
	// Entry 40 - 5F
	0x00000d32, 0x00000d8b, 0x00000de4, 0x00000e48,
	0x00000eaa, 0x00000ef9, 0x00000f50, 0x00000f8e,
	0x00000fca, 0x00001020, 0x00001051, 0x00001086,
	0x000010bb, 0x000010fa, 0x0000113d, 0x0000117c,
	0x000011c7, 0x0000120e, 0x00001258, 0x0000126f,
	0x0000129c, 0x000012bf, 0x000012d0, 0x000012fa,
	0x000012ff, 0x00001304, 0x00001309, 0x00001321,
	0x0000132f, 0x0000135f, 0x0000136c, 0x00001393,
	// Entry 60 - 7F
	0x000013b9, 0x000013d5, 0x000013ea, 0x000013fe,
	0x000015c6, 0x000015d5, 0x000015f3, 0x00001608,
	0x0000161b, 0x00001636, 0x00001657, 0x00001677,
	0x0000168e, 0x0000169b, 0x000016f0, 0x00001751,
	0x000017db, 0x000017fe, 0x00001841, 0x00001859,
	0x00001878, 0x00001896, 0x000018b6, 0x000018d4,
	0x000018e9, 0x000018fe, 0x00001913, 0x0000192d,
	0x00001941, 0x00001946, 0x0000194d, 0x00001955,
	// Entry 80 - 9F
	0x00001962, 0x00001979, 0x00001988, 0x00001993,
	0x000019a2, 0x000019b1, 0x000019c0, 0x000019d7,
} // Size: 568 bytes

const ruData string = "" + // Size: 6615 bytes
	"\x02Временная зона по умолчанию\x02Язык\x02Язык: английский\x02Язык: рус" +
	"ский\x02Уведомления персонажей: вкл.\x02Уведомления персонажей: выкл." +
	"\x02Уведомления аутфитов: вкл.\x02Уведомления аутфитов: выкл.\x02Обновле" +
	"ния заголовка: вкл.\x02Обновления заголовка: выкл.\x02ИНФ\x02ЛАЙТ\x02МЕ" +
	"Д\x02ИНЖ\x02ШТУРМ\x02МАКС\x02Неизвестно\x02Фракция\x02Аутфит\x02Персона" +
	"ж\x02Убийства\x02HS\x02У/C\x02Класс\x02Время\x02[%[1]s] %[2]s (%[3]s) о" +
	"нлайн (%[4]s)\x02%[1]s (%[2]s) онлайн (%[3]s)\x02[%[1]s] %[2]s (%[3]s" +
	") оффлайн (%[4]s)\x02%[1]s (%[2]s) оффлайн (%[3]s)\x02Ошибка загрузки " +
	"аутфита: %[1]s (%[2]s)\x02Ошибка загрузки персонажей: %[1]v (%[2]s)" +
	"\x04\x00\x01 \x15\x02Обновление\x02] члены аутфита:\x04\x01\x0a\x005\x02" +
	"**Добро пожаловать в аутфит:**\x04\x01\x0a\x00#\x02**Покинули аутфит:**" +
	"\x02Ошибка загрузки персонажа: %[1]s\x02Ошибка загрузки объекта: %[1]s" +
	"\x02Трекер статистики запущен\x02Платформа: %[1]s, запущен: %[2]s, остан" +
	"овлен: %[3]s, продолжительность: %[4]s\x0a```\x02Нет данных\x02%[1]s [%" +
	"[2]s] захватил %[3]s (%[4]s) в %[5]s (%[6]s)\x02%[1]s [%[2]s] потерял %[" +
	"3]s (%[4]s) в %[5]s (%[6]s)\x04\x00\x04\x0a\x09\x09\x0a\x8c\x01\x02Plane" +
	"tSide 2 Spy\x0a\x0aПростой бот для PlanetSide 2 аутфитов\x0a\x0a## Ссыл" +
	"ки\x0a\x0a- [GitHub](https://github.com/x0k/ps2-spy)\x02Неверный тип п" +
	"опуляции: %[1]s\x02Ошибка загрузки глобальной популяции (%[1]s)\x02Оши" +
	"бка загрузки %[1]s популяции (%[2]s)\x02Ошибка загрузки контроля террит" +
	"орий для %[1]s\x02Ошибка загрузки тревог для %[1]s (%[2]s)\x02Ошибка за" +
	"грузки глобальных тревог (%[1]s)\x02Ошибка загрузки онлайн участников " +
	"канала %[1]s (%[2]s)\x02Ошибка загрузки аутфитов %[1]v (%[2]s)\x02Ошибк" +
	"а загрузки аутфитов по тегам %[1]v (%[2]s)\x02Ошибка загрузки персонаже" +
	"й %[1]v (%[2]s)\x02Ошибка сохранения настроек подписки для канала %[1]" +
	"s (%[2]s)\x02Настройки сохранены, но не удалось загрузить теги аутфитов" +
	" %[1]v (%[2]s)\x02Настройки сохранены, но не удалось загрузить имена пе" +
	"рсонажей %[1]v (%[2]s)\x02Нечего отслеживать, пожалуйста, установите " +
	"настройки отслеживания\x02Неверная команда отслеживания статистики: %[" +
	"1]s\x02Не удалось запустить отслеживание статистики\x02Отслеживание стат" +
	"истики не запущено\x02Не удалось остановить отслеживание статистики\x02" +
	"Отслеживание статистики скоро запустится\x02Отслеживание статистики ско" +
	"ро остановится\x02Ошибка загрузки задач отслеживания статистики\x02Ошиб" +
	"ка загрузки задачи отслеживания статистики\x02Ошибка удаления задачи от" +
	"слеживания статистики\x02Состояние задачи отслеживания статистики не на" +
	"йдено\x02Ошибка загрузки настроек подписки для канала %[1]s (%[2]s)" +
	"\x02Не удалось загрузить теги аутфитов %[1]v (%[2]s)\x02Не удалось загру" +
	"зить имена персонажей %[1]v (%[2]s)\x02Ошибка загрузки данных канала %" +
	"[1]s\x02Ошибка извлечения значения поля\x02Ошибка сохранения значения по" +
	"ля для канала %[1]s\x02Настройки отслеживания (PC)\x02Настройки отслежи" +
	"вания (PS4 EU)\x02Настройки отслеживания (PS4 US)\x02Какие аутфиты хоти" +
	"те отслеживать?\x02Введите теги аутфитов через запятую\x02Каких игроков" +
	" хотите отслеживать?\x02Введите имена персонажей через запятую\x02Невоз" +
	"можно распознать локализацию %[1]q\x02Для этого канала был установлен я" +
	"зык %[1]q\x02%[1]d・онлайн\x02Нет персонажей онлайн\x02Персонажи онла" +
	"йн:\x02] аутфит (\x04\x01\x0a\x00%\x02**Другие персонажи:**\x02ТР\x02Н" +
	"К\x02СВ\x02Источник: %[1]s\x02%[1]s - %[2]d\x02Глобальная популяция - %" +
	"[1]d\x02Период\x02%[1]s - %[2]s (Кончится %[3]s)\x02Контроль территорий" +
	"\x02%[1]s - Нет тревог\x02%[1]s тревоги\x02Нет тревог\x04\x00\x01\x0a" +
	"\xc2\x03\x02Примечание:\x0a- Время указано в %[1]q временной зоне. Это м" +
	"ожет быть изменено в настройках канала;\x0a- Максимальное количество за" +
	"дач для канала - %[2]d;\x0a- Вы можете редактировать задачу, нажав на н" +
	"ее;\x0a- Кнопка “Удалить” удаляет немедленно без подтверждения.\x02Удал" +
	"ить\x02Добавить задачу\x02Предыдущая\x02Следующая\x02Час начала: %[1]d" +
	"\x02Минута начала: %[1]d\x02Длительность: %[1]s\x02Подтвердить\x02Отмена" +
	"\x02Максимальное количество задач для канала - %[1]d\x02Превышена максим" +
	"альная длительность задачи (%[1]s): %[2]s\x02Ваша задача (%[1]s, %[2]s," +
	" %[3]s) пересекается с существующей задачей (%[4]s, %[5]s, %[6]s)\x02ч" +
	"то-то пошло не так\x04\x00\x01\x0a>\x02Настройки обновлены.\x0a\x0a**А" +
	"утфиты:**\x02Нет аутфитов\x04\x02\x0a\x0a\x01\x0a\x18\x02**Персонажи:**" +
	"\x02Нет персонажей\x04\x00\x01 \x1b\x02Разблокирован\x04\x00\x01 \x19" +
	"\x02Заблокирован\x02) фракцией `\x04\x01\x0a\x00\x10\x02Статус: _\x02Ста" +
	"бильный\x02Не стабильный\x02_\x0aТревоги: _\x02Да\x02Нет\x02%[1]dм\x04" +
	"\x00\x01 \x08\x02%[1]dч\x02Понедельник\x02Вторник\x02Среда\x02Четверг" +
	"\x02Пятница\x02Суббота\x02Воскресенье"

	// Total table size 11428 bytes (11KiB); checksum: 4BB52C65
