// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"\n\n**Characters:**\n":        85,
	"\n**Left the outfit:**":       24,
	"\n**Other characters:**":      70,
	"\n**Welcome to the outfit:**": 23,
	"\nStatus: _":                  90,
	"# PlanetSide 2 Spy\n\nSimple discord bot for PlanetSide 2 outfits\n\n## Links\n\n- [GitHub](https://github.com/x0k/ps2-spy)\n\t\t\n": 32,
	"%dh ":                                97,
	"%dm":                                 96,
	"%d・online":                           66,
	"%s (%s) is now offline (%s)":         18,
	"%s (%s) is now online (%s)":          16,
	"%s - %d":                             75,
	"%s - %s (Ends %s)":                   78,
	"%s - No alerts":                      80,
	"%s [%s] captured %s (%s) on %s (%s)": 30,
	"%s [%s] lost %s (%s) on %s (%s)":     31,
	"%s alerts":                           81,
	") by `":                              89,
	"Character":                           9,
	"Characters online:":                  68,
	"Duration":                            14,
	"ENG":                                 3,
	"Enter the character names separated by comma": 62,
	"Enter the outfit tags separated by comma":     60,
	"Faction":                                              7,
	"Failed to load %s population with %s":                 35,
	"Failed to load %s territory control":                  36,
	"Failed to load character names for %v (%s)":           55,
	"Failed to load character: %s":                         25,
	"Failed to load characters %v (%s)":                    42,
	"Failed to load characters: %v (%s)":                   20,
	"Failed to load facility: %s":                          26,
	"Failed to load global alerts from %s":                 38,
	"Failed to load global population with %s":             34,
	"Failed to load online members for %s channel (%s)":    39,
	"Failed to load outfit tags for %v (%s)":               54,
	"Failed to load outfit: %s (%s)":                       19,
	"Failed to load outfits %v (%s)":                       40,
	"Failed to load outfits by tags %v (%s)":               41,
	"Failed to load tracking settings for %s channel (%s)": 53,
	"Failed to load world alerts for %s from %s":           37,
	"Failed to parse language %q":                          63,
	"Failed to save language %q":                           64,
	"Failed to save tracking settings for %s channel (%s)": 43,
	"Failed to start stats tracker":                        48,
	"Failed to stop stats tracker":                         50,
	"HA":                                                   4,
	"HS":                                                   11,
	"INF":                                                  0,
	"Invalid population type: %s":                          33,
	"Invalid stats tracker subcommand: %s":                 47,
	"KD":                                                   12,
	"Kills":                                                10,
	"LA":                                                   1,
	"Language for this channel has been set to %q":         65,
	"Loadout":              13,
	"Locked ":              88,
	"MAX":                  5,
	"MED":                  2,
	"NC":                   72,
	"No":                   95,
	"No alerts":            82,
	"No characters":        86,
	"No characters online": 67,
	"No data collected":    29,
	"No outfits":           84,
	"Nothing to track, please set tracking settings first": 46,
	"Outfit": 8,
	"Period": 77,
	"Platform: %s, started at: %s, stopped: %s, duration: %s\n```":   28,
	"Settings are saved, but failed to load character names %v (%s)": 45,
	"Settings are saved, but failed to load outfit tags %v (%s)":     44,
	"Settings are updated.\n\n**Outfits:**\n":                        83,
	"Source: %s":                             74,
	"Stable":                                 91,
	"Stats tracker started":                  27,
	"Stats tracker will be started soon":     51,
	"Stats tracker will be stopped soon":     52,
	"TR":                                     71,
	"Territory Control":                      79,
	"There is no stats tracker to stop":      49,
	"Total population - %d":                  76,
	"Tracking Settings (PC)":                 56,
	"Tracking Settings (PS4 EU)":             57,
	"Tracking Settings (PS4 US)":             58,
	"Unknown":                                6,
	"Unlocked ":                              87,
	"Unstable":                               92,
	"Update of ":                             21,
	"VS":                                     73,
	"Which characters do you want to track?": 61,
	"Which outfits do you want to track?":    59,
	"Yes":                                    94,
	"[%s] %s (%s) is now offline (%s)":       17,
	"[%s] %s (%s) is now online (%s)":        15,
	"] outfit (":                             69,
	"] outfit members:":                      22,
	"_\nAlerts: _":                           93,
}

var enIndex = []uint32{ // 99 elements
	// Entry 0 - 1F
	0x00000000, 0x00000004, 0x00000007, 0x0000000b,
	0x0000000f, 0x00000012, 0x00000016, 0x0000001e,
	0x00000026, 0x0000002d, 0x00000037, 0x0000003d,
	0x00000040, 0x00000043, 0x0000004b, 0x00000054,
	0x00000080, 0x000000a4, 0x000000d1, 0x000000f6,
	0x0000011b, 0x00000144, 0x00000153, 0x00000165,
	0x00000185, 0x0000019f, 0x000001bf, 0x000001de,
	0x000001f4, 0x0000023c, 0x0000024e, 0x00000284,
	// Entry 20 - 3F
	0x000002b6, 0x00000334, 0x00000353, 0x0000037f,
	0x000003aa, 0x000003d1, 0x00000402, 0x0000042a,
	0x00000462, 0x00000487, 0x000004b4, 0x000004dc,
	0x00000517, 0x00000558, 0x0000059d, 0x000005d2,
	0x000005fa, 0x00000618, 0x0000063a, 0x00000657,
	0x0000067a, 0x0000069d, 0x000006d8, 0x00000705,
	0x00000736, 0x0000074d, 0x00000768, 0x00000783,
	0x000007a7, 0x000007d0, 0x000007f7, 0x00000824,
	// Entry 40 - 5F
	0x00000843, 0x00000861, 0x00000891, 0x000008a0,
	0x000008b5, 0x000008c8, 0x000008d3, 0x000008ee,
	0x000008f1, 0x000008f4, 0x000008f7, 0x00000905,
	0x00000913, 0x0000092c, 0x00000933, 0x0000094e,
	0x00000960, 0x00000972, 0x0000097f, 0x00000989,
	0x000009b2, 0x000009bd, 0x000009d4, 0x000009e2,
	0x000009f0, 0x000009fc, 0x00000a03, 0x00000a12,
	0x00000a19, 0x00000a22, 0x00000a2e, 0x00000a32,
	// Entry 60 - 7F
	0x00000a35, 0x00000a3c, 0x00000a48,
} // Size: 420 bytes

const enData string = "" + // Size: 2632 bytes
	"\x02INF\x02LA\x02MED\x02ENG\x02HA\x02MAX\x02Unknown\x02Faction\x02Outfit" +
	"\x02Character\x02Kills\x02HS\x02KD\x02Loadout\x02Duration\x02[%[1]s] %[2" +
	"]s (%[3]s) is now online (%[4]s)\x02%[1]s (%[2]s) is now online (%[3]s)" +
	"\x02[%[1]s] %[2]s (%[3]s) is now offline (%[4]s)\x02%[1]s (%[2]s) is now" +
	" offline (%[3]s)\x02Failed to load outfit: %[1]s (%[2]s)\x02Failed to lo" +
	"ad characters: %[1]v (%[2]s)\x04\x00\x01 \x0a\x02Update of\x02] outfit m" +
	"embers:\x04\x01\x0a\x00\x1b\x02**Welcome to the outfit:**\x04\x01\x0a" +
	"\x00\x15\x02**Left the outfit:**\x02Failed to load character: %[1]s\x02F" +
	"ailed to load facility: %[1]s\x02Stats tracker started\x02Platform: %[1]" +
	"s, started at: %[2]s, stopped: %[3]s, duration: %[4]s\x0a```\x02No data " +
	"collected\x02%[1]s [%[2]s] captured %[3]s (%[4]s) on %[5]s (%[6]s)\x02%[" +
	"1]s [%[2]s] lost %[3]s (%[4]s) on %[5]s (%[6]s)\x04\x00\x04\x0a\x09\x09" +
	"\x0av\x02# PlanetSide 2 Spy\x0a\x0aSimple discord bot for PlanetSide 2 o" +
	"utfits\x0a\x0a## Links\x0a\x0a- [GitHub](https://github.com/x0k/ps2-spy)" +
	"\x02Invalid population type: %[1]s\x02Failed to load global population w" +
	"ith %[1]s\x02Failed to load %[1]s population with %[2]s\x02Failed to loa" +
	"d %[1]s territory control\x02Failed to load world alerts for %[1]s from " +
	"%[2]s\x02Failed to load global alerts from %[1]s\x02Failed to load onlin" +
	"e members for %[1]s channel (%[2]s)\x02Failed to load outfits %[1]v (%[2" +
	"]s)\x02Failed to load outfits by tags %[1]v (%[2]s)\x02Failed to load ch" +
	"aracters %[1]v (%[2]s)\x02Failed to save tracking settings for %[1]s cha" +
	"nnel (%[2]s)\x02Settings are saved, but failed to load outfit tags %[1]v" +
	" (%[2]s)\x02Settings are saved, but failed to load character names %[1]v" +
	" (%[2]s)\x02Nothing to track, please set tracking settings first\x02Inva" +
	"lid stats tracker subcommand: %[1]s\x02Failed to start stats tracker\x02" +
	"There is no stats tracker to stop\x02Failed to stop stats tracker\x02Sta" +
	"ts tracker will be started soon\x02Stats tracker will be stopped soon" +
	"\x02Failed to load tracking settings for %[1]s channel (%[2]s)\x02Failed" +
	" to load outfit tags for %[1]v (%[2]s)\x02Failed to load character names" +
	" for %[1]v (%[2]s)\x02Tracking Settings (PC)\x02Tracking Settings (PS4 E" +
	"U)\x02Tracking Settings (PS4 US)\x02Which outfits do you want to track?" +
	"\x02Enter the outfit tags separated by comma\x02Which characters do you " +
	"want to track?\x02Enter the character names separated by comma\x02Failed" +
	" to parse language %[1]q\x02Failed to save language %[1]q\x02Language fo" +
	"r this channel has been set to %[1]q\x02%[1]d・online\x02No characters on" +
	"line\x02Characters online:\x02] outfit (\x04\x01\x0a\x00\x16\x02**Other " +
	"characters:**\x02TR\x02NC\x02VS\x02Source: %[1]s\x02%[1]s - %[2]d\x02Tot" +
	"al population - %[1]d\x02Period\x02%[1]s - %[2]s (Ends %[3]s)\x02Territo" +
	"ry Control\x02%[1]s - No alerts\x02%[1]s alerts\x02No alerts\x04\x00\x01" +
	"\x0a$\x02Settings are updated.\x0a\x0a**Outfits:**\x02No outfits\x04\x02" +
	"\x0a\x0a\x01\x0a\x10\x02**Characters:**\x02No characters\x04\x00\x01 " +
	"\x09\x02Unlocked\x04\x00\x01 \x07\x02Locked\x02) by `\x04\x01\x0a\x00" +
	"\x0a\x02Status: _\x02Stable\x02Unstable\x02_\x0aAlerts: _\x02Yes\x02No" +
	"\x02%[1]dm\x04\x00\x01 \x07\x02%[1]dh"

var ruIndex = []uint32{ // 99 elements
	// Entry 0 - 1F
	0x00000000, 0x00000007, 0x00000010, 0x00000017,
	0x0000001e, 0x00000029, 0x00000032, 0x00000047,
	0x00000056, 0x00000063, 0x00000074, 0x00000085,
	0x00000088, 0x0000008d, 0x00000098, 0x000000a3,
	0x000000d0, 0x000000f5, 0x00000124, 0x0000014b,
	0x00000187, 0x000001cb, 0x000001e5, 0x00000202,
	0x0000023c, 0x00000264, 0x0000029c, 0x000002d0,
	0x00000301, 0x0000037e, 0x00000392, 0x000003d0,
	// Entry 20 - 3F
	0x0000040c, 0x000004a1, 0x000004d5, 0x00000525,
	0x00000564, 0x000005b5, 0x000005f5, 0x0000063d,
	0x0000069a, 0x000006d7, 0x00000724, 0x00000767,
	0x000007cd, 0x0000084a, 0x000008cf, 0x0000094f,
	0x000009a4, 0x000009f9, 0x00000a3d, 0x00000a94,
	0x00000ae2, 0x00000b32, 0x00000b94, 0x00000be3,
	0x00000c3a, 0x00000c6b, 0x00000ca0, 0x00000cd5,
	0x00000d14, 0x00000d57, 0x00000d96, 0x00000de1,
	// Entry 40 - 5F
	0x00000e28, 0x00000e6e, 0x00000eb8, 0x00000ecf,
	0x00000efc, 0x00000f1f, 0x00000f30, 0x00000f5a,
	0x00000f5f, 0x00000f64, 0x00000f69, 0x00000f81,
	0x00000f8f, 0x00000fbf, 0x00000fcc, 0x00000ff3,
	0x00001019, 0x00001035, 0x0000104a, 0x0000105e,
	0x000010a1, 0x000010b9, 0x000010d8, 0x000010f6,
	0x00001116, 0x00001134, 0x00001149, 0x0000115e,
	0x00001173, 0x0000118d, 0x000011a1, 0x000011a6,
	// Entry 60 - 7F
	0x000011ad, 0x000011b5, 0x000011c2,
} // Size: 420 bytes

const ruData string = "" + // Size: 4546 bytes
	"\x02ИНФ\x02ЛАЙТ\x02МЕД\x02ИНЖ\x02ШТУРМ\x02МАКС\x02Неизвестно\x02Фракция" +
	"\x02Аутфит\x02Персонаж\x02Убийства\x02HS\x02У/C\x02Класс\x02Время\x02[%[" +
	"1]s] %[2]s (%[3]s) онлайн (%[4]s)\x02%[1]s (%[2]s) онлайн (%[3]s)\x02[" +
	"%[1]s] %[2]s (%[3]s) оффлайн (%[4]s)\x02%[1]s (%[2]s) оффлайн (%[3]s)" +
	"\x02Ошибка загрузки аутфита: %[1]s (%[2]s)\x02Ошибка загрузки персонажеи" +
	"̆: %[1]v (%[2]s)\x04\x00\x01 \x15\x02Обновление\x02] члены аутфита:\x04" +
	"\x01\x0a\x005\x02**Добро пожаловать в аутфит:**\x04\x01\x0a\x00#\x02**По" +
	"кинули аутфит:**\x02Ошибка загрузки персонажа: %[1]s\x02Ошибка загрузки" +
	" объекта: %[1]s\x02Трекер статистики запущен\x02Платформа: %[1]s, запуще" +
	"н: %[2]s, остановлен: %[3]s, продолжительность: %[4]s\x0a```\x02Нет дан" +
	"ных\x02%[1]s [%[2]s] захватил %[3]s (%[4]s) в %[5]s (%[6]s)\x02%[1]s [%" +
	"[2]s] потерял %[3]s (%[4]s) в %[5]s (%[6]s)\x04\x00\x04\x0a\x09\x09\x0a" +
	"\x8c\x01\x02PlanetSide 2 Spy\x0a\x0aПростой бот для PlanetSide 2 аутфит" +
	"ов\x0a\x0a## Ссылки\x0a\x0a- [GitHub](https://github.com/x0k/ps2-spy)" +
	"\x02Неверный тип популяции: %[1]s\x02Ошибка загрузки глобальной популя" +
	"ции (%[1]s)\x02Ошибка загрузки %[1]s популяции (%[2]s)\x02Ошибка загруз" +
	"ки контроля территорий для %[1]s\x02Ошибка загрузки тревог для %[1]s (%" +
	"[2]s)\x02Ошибка загрузки глобальных тревог (%[1]s)\x02Ошибка загрузки он" +
	"лайн участников канала %[1]s (%[2]s)\x02Ошибка загрузки аутфитов %[1]v" +
	" (%[2]s)\x02Ошибка загрузки аутфитов по тегам %[1]v (%[2]s)\x02Ошибка за" +
	"грузки персонажей %[1]v (%[2]s)\x02Ошибка сохранения настроек подписки" +
	" для канала %[1]s (%[2]s)\x02Настройки сохранены, но не удалось загрузи" +
	"ть теги аутфитов %[1]v (%[2]s)\x02Настройки сохранены, но не удалось з" +
	"агрузить имена персонажей %[1]v (%[2]s)\x02Нечего отслеживать, пожалуи" +
	"̆ста, установите настройки отслеживания\x02Неверная команда отслеживан" +
	"ия статистики: %[1]s\x02Не удалось запустить отслеживание статистики" +
	"\x02Отслеживание статистики не запущено\x02Не удалось остановить отслежи" +
	"вание статистики\x02Отслеживание статистики скоро запустится\x02Отслежи" +
	"вание статистики скоро остановится\x02Ошибка загрузки настроек подписки" +
	" для канала %[1]s (%[2]s)\x02Не удалось загрузить теги аутфитов %[1]v (%" +
	"[2]s)\x02Не удалось загрузить имена персонажей %[1]v (%[2]s)\x02Настрой" +
	"ки отслеживания (PC)\x02Настройки отслеживания (PS4 EU)\x02Настройки от" +
	"слеживания (PS4 US)\x02Какие аутфиты хотите отслеживать?\x02Введите тег" +
	"и аутфитов через запятую\x02Каких игроков хотите отслеживать?\x02Введит" +
	"е имена персонажей через запятую\x02Невозможно распознать локализацию " +
	"%[1]q\x02Ошибка при сохранении локализации %[1]q\x02Для этого канала был" +
	" установлен язык %[1]q\x02%[1]d・онлайн\x02Нет персонажей онлайн\x02Пе" +
	"рсонажи онлайн:\x02] аутфит (\x04\x01\x0a\x00%\x02**Другие персонажи:*" +
	"*\x02ТР\x02НК\x02СВ\x02Источник: %[1]s\x02%[1]s - %[2]d\x02Глобальная по" +
	"пуляция - %[1]d\x02Период\x02%[1]s - %[2]s (Кончится %[3]s)\x02Контроль" +
	" территорий\x02%[1]s - Нет тревог\x02%[1]s тревоги\x02Нет тревог\x04\x00" +
	"\x01\x0a>\x02Настройки обновлены.\x0a\x0a**Аутфиты:**\x02Нет аутфитов" +
	"\x04\x02\x0a\x0a\x01\x0a\x18\x02**Персонажи:**\x02Нет персонажей\x04" +
	"\x00\x01 \x1b\x02Разблокирован\x04\x00\x01 \x19\x02Заблокирован\x02) фра" +
	"кцией `\x04\x01\x0a\x00\x10\x02Статус: _\x02Стабильный\x02Не стабильный" +
	"\x02_\x0aТревоги: _\x02Да\x02Нет\x02%[1]dм\x04\x00\x01 \x08\x02%[1]dч"

	// Total table size 8018 bytes (7KiB); checksum: ED30D43B
