// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"\n\n**Characters:**\n":        119,
	"\n**Left the outfit:**":       34,
	"\n**Other characters:**":      87,
	"\n**Welcome to the outfit:**": 33,
	"\n- %s, %02d:%02d, %s":        107,
	"\n- No tasks were found":      106,
	"\nStatus: _":                  124,
	"# PlanetSide 2 Spy\n\nSimple discord bot for PlanetSide 2 outfits\n\n## Links\n\n- [GitHub](https://github.com/x0k/ps2-spy)\n\t\t\n": 42,
	"%dh ":                                131,
	"%dm":                                 130,
	"%d・online":                           82,
	"%s (%s) is now offline (%s)":         28,
	"%s (%s) is now online (%s)":          26,
	"%s - %d":                             92,
	"%s - %s (Ends %s)":                   95,
	"%s - No alerts":                      97,
	"%s [%s] captured %s (%s) on %s (%s)": 40,
	"%s [%s] lost %s (%s) on %s (%s)":     41,
	"%s alerts":                           98,
	") by `":                              123,
	"Add new task":                        102,
	"Cancel":                              112,
	"Character":                           19,
	"Character notifications: off":        5,
	"Character notifications: on":         4,
	"Characters online:":                  85,
	"Default timezone":                    0,
	"Duration":                            24,
	"Duration too long: expected max %s got %s": 114,
	"Duration: %s": 110,
	"ENG":          13,
	"Enter the character names separated by comma": 79,
	"Enter the outfit tags separated by comma":     77,
	"Faction":                                              17,
	"Failed to extract field value":                        71,
	"Failed to load %s channel":                            70,
	"Failed to load %s population with %s":                 45,
	"Failed to load %s territory control":                  46,
	"Failed to load character names for %v (%s)":           69,
	"Failed to load character: %s":                         35,
	"Failed to load characters %v (%s)":                    52,
	"Failed to load characters: %v (%s)":                   30,
	"Failed to load facility: %s":                          36,
	"Failed to load global alerts from %s":                 48,
	"Failed to load global population with %s":             44,
	"Failed to load online members for %s channel (%s)":    49,
	"Failed to load outfit tags for %v (%s)":               68,
	"Failed to load outfit: %s (%s)":                       29,
	"Failed to load outfits %v (%s)":                       50,
	"Failed to load outfits by tags %v (%s)":               51,
	"Failed to load stats tracker task":                    64,
	"Failed to load stats tracker tasks":                   63,
	"Failed to load tracking settings for %s channel (%s)": 67,
	"Failed to load world alerts for %s from %s":           47,
	"Failed to parse language %q":                          80,
	"Failed to remove stats tracker task":                  65,
	"Failed to save field value for %s channel":            72,
	"Failed to save tracking settings for %s channel (%s)": 53,
	"Failed to start stats tracker":                        58,
	"Failed to stop stats tracker":                         60,
	"Friday":                                               136,
	"HA":                                                   14,
	"HS":                                                   21,
	"INF":                                                  10,
	"Invalid population type: %s":                          43,
	"Invalid stats tracker subcommand: %s":                 57,
	"KD":                                                   22,
	"Kills":                                                20,
	"LA":                                                   11,
	"Language":                                             1,
	"Language for this channel has been set to %q":         81,
	"Language: english":                                    2,
	"Language: russian":                                    3,
	"Loadout":                                              23,
	"Locked ":                                              122,
	"MAX":                                                  15,
	"MED":                                                  12,
	"Max amount of tasks per channel is %d":                113,
	"Monday":                                               132,
	"NC":                                                   89,
	"Next":                                                 104,
	"No":                                                   129,
	"No alerts":                                            99,
	"No characters":                                        120,
	"No characters online":                                 84,
	"No data collected":                                    39,
	"No outfits":                                           118,
	"Notes:\n- The time is specified in the time zone %q. This can be changed in the channel settings;\n- The maximum amount of tasks per channel is %d;\n- You can edit a task by clicking on it;\n- The “Remove” button deletes immediately without confirmation.\n": 100,
	"Nothing to track, please set tracking settings first": 56,
	"Outfit":                    18,
	"Outfit notifications: off": 7,
	"Outfit notifications: on":  6,
	"Period":                    94,
	"Platform: %s, started at: %s, stopped: %s, duration: %s\n```": 38,
	"Previous":  103,
	"Remove":    101,
	"Saturday":  137,
	"Schedule:": 105,
	"Settings are saved, but failed to load character names %v (%s)": 55,
	"Settings are saved, but failed to load outfit tags %v (%s)":     54,
	"Settings are updated.\n\n**Outfits:**\n":                        117,
	"Source: %s":                             91,
	"Stable":                                 125,
	"Starting hour: %d":                      108,
	"Starting minute: %d":                    109,
	"Stats tracker started":                  37,
	"Stats tracker task state not found":     66,
	"Stats tracker will be started soon":     61,
	"Stats tracker will be stopped soon":     62,
	"Submit":                                 111,
	"Sunday":                                 138,
	"TR":                                     88,
	"Territory Control":                      96,
	"There is no stats tracker to stop":      59,
	"Thursday":                               135,
	"Title updates: off":                     9,
	"Title updates: on":                      8,
	"Total population - %d":                  93,
	"Tracking Settings (PC)":                 73,
	"Tracking Settings (PS4 EU)":             74,
	"Tracking Settings (PS4 US)":             75,
	"Tuesday":                                133,
	"Unknown":                                16,
	"Unlocked ":                              121,
	"Unstable":                               126,
	"Update of ":                             31,
	"VS":                                     90,
	"Wednesday":                              134,
	"Which characters do you want to track?": 78,
	"Which outfits do you want to track?":    76,
	"Yes":                                    128,
	"You must have `Manage Channels` permission to use this command":  83,
	"Your task (%s, %s, %s) overlaps with existing task (%s, %s, %s)": 115,
	"[%s] %s (%s) is now offline (%s)":                                27,
	"[%s] %s (%s) is now online (%s)":                                 25,
	"] outfit (":                                                      86,
	"] outfit members:":                                               32,
	"_\nAlerts: _":                                                    127,
	"something went wrong":                                            116,
}

var enIndex = []uint32{ // 140 elements
	// Entry 0 - 1F
	0x00000000, 0x00000011, 0x0000001a, 0x0000002c,
	0x0000003e, 0x0000005a, 0x00000077, 0x00000090,
	0x000000aa, 0x000000bc, 0x000000cf, 0x000000d3,
	0x000000d6, 0x000000da, 0x000000de, 0x000000e1,
	0x000000e5, 0x000000ed, 0x000000f5, 0x000000fc,
	0x00000106, 0x0000010c, 0x0000010f, 0x00000112,
	0x0000011a, 0x00000123, 0x0000014f, 0x00000173,
	0x000001a0, 0x000001c5, 0x000001ea, 0x00000213,
	// Entry 20 - 3F
	0x00000222, 0x00000234, 0x00000254, 0x0000026e,
	0x0000028e, 0x000002ad, 0x000002c3, 0x0000030b,
	0x0000031d, 0x00000353, 0x00000385, 0x00000403,
	0x00000422, 0x0000044e, 0x00000479, 0x000004a0,
	0x000004d1, 0x000004f9, 0x00000531, 0x00000556,
	0x00000583, 0x000005ab, 0x000005e6, 0x00000627,
	0x0000066c, 0x000006a1, 0x000006c9, 0x000006e7,
	0x00000709, 0x00000726, 0x00000749, 0x0000076c,
	// Entry 40 - 5F
	0x0000078f, 0x000007b1, 0x000007d5, 0x000007f8,
	0x00000833, 0x00000860, 0x00000891, 0x000008ae,
	0x000008cc, 0x000008f9, 0x00000910, 0x0000092b,
	0x00000946, 0x0000096a, 0x00000993, 0x000009ba,
	0x000009e7, 0x00000a06, 0x00000a36, 0x00000a45,
	0x00000a84, 0x00000a99, 0x00000aac, 0x00000ab7,
	0x00000ad2, 0x00000ad5, 0x00000ad8, 0x00000adb,
	0x00000ae9, 0x00000af7, 0x00000b10, 0x00000b17,
	// Entry 60 - 7F
	0x00000b32, 0x00000b44, 0x00000b56, 0x00000b63,
	0x00000b6d, 0x00000c78, 0x00000c7f, 0x00000c8c,
	0x00000c95, 0x00000c9a, 0x00000ca4, 0x00000cbf,
	0x00000ce4, 0x00000cf9, 0x00000d10, 0x00000d20,
	0x00000d27, 0x00000d2e, 0x00000d57, 0x00000d87,
	0x00000dd9, 0x00000dee, 0x00000e17, 0x00000e22,
	0x00000e39, 0x00000e47, 0x00000e55, 0x00000e61,
	0x00000e68, 0x00000e77, 0x00000e7e, 0x00000e87,
	// Entry 80 - 9F
	0x00000e93, 0x00000e97, 0x00000e9a, 0x00000ea1,
	0x00000ead, 0x00000eb4, 0x00000ebc, 0x00000ec6,
	0x00000ecf, 0x00000ed6, 0x00000edf, 0x00000ee6,
} // Size: 584 bytes

const enData string = "" + // Size: 3814 bytes
	"\x02Default timezone\x02Language\x02Language: english\x02Language: russi" +
	"an\x02Character notifications: on\x02Character notifications: off\x02Out" +
	"fit notifications: on\x02Outfit notifications: off\x02Title updates: on" +
	"\x02Title updates: off\x02INF\x02LA\x02MED\x02ENG\x02HA\x02MAX\x02Unknow" +
	"n\x02Faction\x02Outfit\x02Character\x02Kills\x02HS\x02KD\x02Loadout\x02D" +
	"uration\x02[%[1]s] %[2]s (%[3]s) is now online (%[4]s)\x02%[1]s (%[2]s) " +
	"is now online (%[3]s)\x02[%[1]s] %[2]s (%[3]s) is now offline (%[4]s)" +
	"\x02%[1]s (%[2]s) is now offline (%[3]s)\x02Failed to load outfit: %[1]s" +
	" (%[2]s)\x02Failed to load characters: %[1]v (%[2]s)\x04\x00\x01 \x0a" +
	"\x02Update of\x02] outfit members:\x04\x01\x0a\x00\x1b\x02**Welcome to t" +
	"he outfit:**\x04\x01\x0a\x00\x15\x02**Left the outfit:**\x02Failed to lo" +
	"ad character: %[1]s\x02Failed to load facility: %[1]s\x02Stats tracker s" +
	"tarted\x02Platform: %[1]s, started at: %[2]s, stopped: %[3]s, duration: " +
	"%[4]s\x0a```\x02No data collected\x02%[1]s [%[2]s] captured %[3]s (%[4]s" +
	") on %[5]s (%[6]s)\x02%[1]s [%[2]s] lost %[3]s (%[4]s) on %[5]s (%[6]s)" +
	"\x04\x00\x04\x0a\x09\x09\x0av\x02# PlanetSide 2 Spy\x0a\x0aSimple discor" +
	"d bot for PlanetSide 2 outfits\x0a\x0a## Links\x0a\x0a- [GitHub](https:/" +
	"/github.com/x0k/ps2-spy)\x02Invalid population type: %[1]s\x02Failed to " +
	"load global population with %[1]s\x02Failed to load %[1]s population wit" +
	"h %[2]s\x02Failed to load %[1]s territory control\x02Failed to load worl" +
	"d alerts for %[1]s from %[2]s\x02Failed to load global alerts from %[1]s" +
	"\x02Failed to load online members for %[1]s channel (%[2]s)\x02Failed to" +
	" load outfits %[1]v (%[2]s)\x02Failed to load outfits by tags %[1]v (%[2" +
	"]s)\x02Failed to load characters %[1]v (%[2]s)\x02Failed to save trackin" +
	"g settings for %[1]s channel (%[2]s)\x02Settings are saved, but failed t" +
	"o load outfit tags %[1]v (%[2]s)\x02Settings are saved, but failed to lo" +
	"ad character names %[1]v (%[2]s)\x02Nothing to track, please set trackin" +
	"g settings first\x02Invalid stats tracker subcommand: %[1]s\x02Failed to" +
	" start stats tracker\x02There is no stats tracker to stop\x02Failed to s" +
	"top stats tracker\x02Stats tracker will be started soon\x02Stats tracker" +
	" will be stopped soon\x02Failed to load stats tracker tasks\x02Failed to" +
	" load stats tracker task\x02Failed to remove stats tracker task\x02Stats" +
	" tracker task state not found\x02Failed to load tracking settings for %[" +
	"1]s channel (%[2]s)\x02Failed to load outfit tags for %[1]v (%[2]s)\x02F" +
	"ailed to load character names for %[1]v (%[2]s)\x02Failed to load %[1]s " +
	"channel\x02Failed to extract field value\x02Failed to save field value f" +
	"or %[1]s channel\x02Tracking Settings (PC)\x02Tracking Settings (PS4 EU)" +
	"\x02Tracking Settings (PS4 US)\x02Which outfits do you want to track?" +
	"\x02Enter the outfit tags separated by comma\x02Which characters do you " +
	"want to track?\x02Enter the character names separated by comma\x02Failed" +
	" to parse language %[1]q\x02Language for this channel has been set to %[" +
	"1]q\x02%[1]d・online\x02You must have `Manage Channels` permission to use" +
	" this command\x02No characters online\x02Characters online:\x02] outfit " +
	"(\x04\x01\x0a\x00\x16\x02**Other characters:**\x02TR\x02NC\x02VS\x02Sour" +
	"ce: %[1]s\x02%[1]s - %[2]d\x02Total population - %[1]d\x02Period\x02%[1]" +
	"s - %[2]s (Ends %[3]s)\x02Territory Control\x02%[1]s - No alerts\x02%[1]" +
	"s alerts\x02No alerts\x04\x00\x01\x0a\x85\x02\x02Notes:\x0a- The time is" +
	" specified in the time zone %[1]q. This can be changed in the channel se" +
	"ttings;\x0a- The maximum amount of tasks per channel is %[2]d;\x0a- You " +
	"can edit a task by clicking on it;\x0a- The “Remove” button deletes imme" +
	"diately without confirmation.\x02Remove\x02Add new task\x02Previous\x02N" +
	"ext\x02Schedule:\x04\x01\x0a\x00\x16\x02- No tasks were found\x04\x01" +
	"\x0a\x00 \x02- %[1]s, %02[2]d:%02[3]d, %[4]s\x02Starting hour: %[1]d\x02" +
	"Starting minute: %[1]d\x02Duration: %[1]s\x02Submit\x02Cancel\x02Max amo" +
	"unt of tasks per channel is %[1]d\x02Duration too long: expected max %[1" +
	"]s got %[2]s\x02Your task (%[1]s, %[2]s, %[3]s) overlaps with existing t" +
	"ask (%[4]s, %[5]s, %[6]s)\x02something went wrong\x04\x00\x01\x0a$\x02Se" +
	"ttings are updated.\x0a\x0a**Outfits:**\x02No outfits\x04\x02\x0a\x0a" +
	"\x01\x0a\x10\x02**Characters:**\x02No characters\x04\x00\x01 \x09\x02Unl" +
	"ocked\x04\x00\x01 \x07\x02Locked\x02) by `\x04\x01\x0a\x00\x0a\x02Status" +
	": _\x02Stable\x02Unstable\x02_\x0aAlerts: _\x02Yes\x02No\x02%[1]dm\x04" +
	"\x00\x01 \x07\x02%[1]dh\x02Monday\x02Tuesday\x02Wednesday\x02Thursday" +
	"\x02Friday\x02Saturday\x02Sunday"

var ruIndex = []uint32{ // 140 elements
	// Entry 0 - 1F
	0x00000000, 0x00000034, 0x0000003d, 0x0000005c,
	0x00000075, 0x000000aa, 0x000000e1, 0x0000011c,
	0x00000159, 0x0000018a, 0x000001bd, 0x000001c4,
	0x000001cd, 0x000001d4, 0x000001db, 0x000001e6,
	0x000001ef, 0x00000204, 0x00000213, 0x00000223,
	0x00000234, 0x00000245, 0x00000248, 0x0000024d,
	0x00000258, 0x00000263, 0x00000290, 0x000002b5,
	0x000002e2, 0x00000307, 0x0000034f, 0x00000393,
	// Entry 20 - 3F
	0x000003ad, 0x000003d6, 0x0000041e, 0x00000454,
	0x0000048c, 0x000004c0, 0x000004f1, 0x0000056e,
	0x00000582, 0x000005dd, 0x00000636, 0x000006cd,
	0x00000701, 0x00000751, 0x00000790, 0x000007f4,
	0x00000849, 0x00000891, 0x000008ee, 0x00000935,
	0x0000098c, 0x000009cf, 0x00000a3d, 0x00000ac4,
	0x00000b49, 0x00000bc9, 0x00000c1e, 0x00000c73,
	0x00000cb7, 0x00000d0e, 0x00000d5c, 0x00000dac,
	// Entry 40 - 5F
	0x00000e03, 0x00000e5c, 0x00000eb5, 0x00000f19,
	0x00000f7b, 0x00000fd4, 0x0000102b, 0x00001069,
	0x000010a5, 0x000010fb, 0x0000112c, 0x00001161,
	0x00001196, 0x000011e1, 0x0000122e, 0x0000126d,
	0x000012b8, 0x000012ff, 0x00001349, 0x00001360,
	0x000013de, 0x0000140b, 0x0000142e, 0x0000144d,
	0x00001477, 0x0000147c, 0x00001481, 0x00001486,
	0x0000149e, 0x000014ac, 0x000014dc, 0x000014e9,
	// Entry 60 - 7F
	0x00001510, 0x00001536, 0x00001552, 0x00001567,
	0x0000157b, 0x00001743, 0x00001752, 0x00001770,
	0x00001785, 0x00001798, 0x000017ae, 0x000017d8,
	0x000017fd, 0x00001818, 0x00001839, 0x00001859,
	0x00001870, 0x0000187d, 0x000018d2, 0x00001933,
	0x000019bd, 0x000019e0, 0x00001a23, 0x00001a45,
	0x00001a64, 0x00001a82, 0x00001aa2, 0x00001ac0,
	0x00001ad5, 0x00001aea, 0x00001aff, 0x00001b19,
	// Entry 80 - 9F
	0x00001b2d, 0x00001b32, 0x00001b39, 0x00001b41,
	0x00001b4e, 0x00001b65, 0x00001b74, 0x00001b7f,
	0x00001b8e, 0x00001b9d, 0x00001bac, 0x00001bc3,
} // Size: 584 bytes

const ruData string = "" + // Size: 7107 bytes
	"\x02Временная зона по умолчанию\x02Язык\x02Язык: английский\x02Язык: рус" +
	"ский\x02Уведомления персонажей: вкл.\x02Уведомления персонажей: выкл." +
	"\x02Уведомления подразделений: вкл.\x02Уведомления подразделений: выкл." +
	"\x02Обновления заголовка: вкл.\x02Обновления заголовка: выкл.\x02ИНФ\x02" +
	"ЛАЙТ\x02МЕД\x02ИНЖ\x02ШТУРМ\x02МАКС\x02Неизвестно\x02Фракция\x02Подразд" +
	".\x02Персонаж\x02Убийства\x02HS\x02У/C\x02Класс\x02Время\x02[%[1]s] %[2]" +
	"s (%[3]s) онлайн (%[4]s)\x02%[1]s (%[2]s) онлайн (%[3]s)\x02[%[1]s] %[" +
	"2]s (%[3]s) офлайн (%[4]s)\x02%[1]s (%[2]s) офлайн (%[3]s)\x02Ошибка з" +
	"агрузки подразделения: %[1]s (%[2]s)\x02Ошибка загрузки персонажей: %[" +
	"1]v (%[2]s)\x04\x00\x01 \x15\x02Обновление\x02] члены подразделения:\x04" +
	"\x01\x0a\x00C\x02**Добро пожаловать в подразделение:**\x04\x01\x0a\x001" +
	"\x02**Покинули подразделение:**\x02Ошибка загрузки персонажа: %[1]s\x02О" +
	"шибка загрузки объекта: %[1]s\x02Трекер статистики запущен\x02Платформа" +
	": %[1]s, запущен: %[2]s, остановлен: %[3]s, продолжительность: %[4]s\x0a" +
	"```\x02Нет данных\x02Подразделение %[1]s [%[2]s] захватило %[3]s (%[4]s)" +
	" в %[5]s (%[6]s)\x02Подразделение %[1]s [%[2]s] потеряло %[3]s (%[4]s) в" +
	" %[5]s (%[6]s)\x04\x00\x04\x0a\x09\x09\x0a\x8e\x01\x02PlanetSide 2 Spy" +
	"\x0a\x0aЧат-бот для PlanetSide 2 подразделений\x0a\x0a## Ссылки\x0a\x0a" +
	"- [GitHub](https://github.com/x0k/ps2-spy)\x02Неверный тип популяции: %" +
	"[1]s\x02Ошибка загрузки глобальной популяции (%[1]s)\x02Ошибка загрузки" +
	" %[1]s популяции (%[2]s)\x02Ошибка загрузки состояния контроля территори" +
	"й для %[1]s\x02Ошибка загрузки актуальных тревог для %[1]s (%[2]s)\x02О" +
	"шибка загрузки глобальных тревог (%[1]s)\x02Ошибка загрузки онлайн уча" +
	"стников канала %[1]s (%[2]s)\x02Ошибка загрузки подразделений %[1]v (%[" +
	"2]s)\x02Ошибка загрузки подразделений по тегам %[1]v (%[2]s)\x02Ошибка з" +
	"агрузки персонажей %[1]v (%[2]s)\x02Ошибка сохранения настроек отслежи" +
	"вания для канала %[1]s (%[2]s)\x02Настройки сохранены, но не удалось з" +
	"агрузить теги подразделений %[1]v (%[2]s)\x02Настройки сохранены, но н" +
	"е удалось загрузить имена персонажей %[1]v (%[2]s)\x02Нечего отслежива" +
	"ть, пожалуйста, установите настройки отслеживания\x02Неверная команда" +
	" отслеживания статистики: %[1]s\x02Не удалось запустить отслеживание ста" +
	"тистики\x02Отслеживание статистики не запущено\x02Не удалось остановить" +
	" отслеживание статистики\x02Отслеживание статистики скоро запустится\x02" +
	"Отслеживание статистики скоро остановится\x02Ошибка загрузки задач отсл" +
	"еживания статистики\x02Ошибка загрузки задачи отслеживания статистики" +
	"\x02Ошибка удаления задачи отслеживания статистики\x02Состояние задачи о" +
	"тслеживания статистики не найдено\x02Ошибка загрузки настроек подписки" +
	" для канала %[1]s (%[2]s)\x02Не удалось загрузить теги подразделений %[1" +
	"]v (%[2]s)\x02Не удалось загрузить имена персонажей %[1]v (%[2]s)\x02Ош" +
	"ибка загрузки данных канала %[1]s\x02Ошибка извлечения значения поля" +
	"\x02Ошибка сохранения значения поля для канала %[1]s\x02Настройки отслеж" +
	"ивания (PC)\x02Настройки отслеживания (PS4 EU)\x02Настройки отслеживани" +
	"я (PS4 US)\x02Какие подразделения хотите отслеживать?\x02Введите теги п" +
	"одразделений через запятую\x02Каких игроков хотите отслеживать?\x02Введ" +
	"ите имена персонажей через запятую\x02Невозможно распознать локализаци" +
	"ю %[1]q\x02Для этого канала был установлен язык %[1]q\x02%[1]d・онлайн" +
	"\x02Вы должны иметь разрешение `Manage Channels` чтобы использовать эту " +
	"команду\x02Нет персонажей онлайн\x02Персонажи онлайн:\x02] подраздел" +
	"ение (\x04\x01\x0a\x00%\x02**Другие персонажи:**\x02ТР\x02НК\x02СВ\x02И" +
	"сточник: %[1]s\x02%[1]s - %[2]d\x02Глобальная популяция - %[1]d\x02Пери" +
	"од\x02%[1]s - %[2]s (Кончится %[3]s)\x02Контроль территорий\x02%[1]s - " +
	"Нет тревог\x02%[1]s тревоги\x02Нет тревог\x04\x00\x01\x0a\xc2\x03\x02Пр" +
	"имечание:\x0a- Время указано в %[1]q временной зоне. Это может быть изм" +
	"енено в настройках канала;\x0a- Максимальное количество задач для канал" +
	"а - %[2]d;\x0a- Вы можете редактировать задачу, нажав на нее;\x0a- Кноп" +
	"ка “Удалить” удаляет немедленно без подтверждения.\x02Удалить\x02Добави" +
	"ть задачу\x02Предыдущая\x02Следующая\x02Расписание:\x04\x01\x0a\x00%" +
	"\x02- Задачи не найдены\x04\x01\x0a\x00 \x02- %[1]s, %02[2]d:%02[3]d, %" +
	"[4]s\x02Час начала: %[1]d\x02Минута начала: %[1]d\x02Длительность: %[1]s" +
	"\x02Подтвердить\x02Отмена\x02Максимальное количество задач для канала - " +
	"%[1]d\x02Превышена максимальная длительность задачи (%[1]s): %[2]s\x02Ва" +
	"ша задача (%[1]s, %[2]s, %[3]s) пересекается с существующей задачей (" +
	"%[4]s, %[5]s, %[6]s)\x02что-то пошло не так\x04\x00\x01\x0a>\x02Настрой" +
	"ки обновлены.\x0a\x0a**Аутфиты:**\x02Нет подразделений\x04\x02\x0a\x0a" +
	"\x01\x0a\x18\x02**Персонажи:**\x02Нет персонажей\x04\x00\x01 \x1b\x02Ра" +
	"зблокирован\x04\x00\x01 \x19\x02Заблокирован\x02) фракцией `\x04\x01" +
	"\x0a\x00\x10\x02Статус: _\x02Стабильный\x02Не стабильный\x02_\x0aТревоги" +
	": _\x02Да\x02Нет\x02%[1]dм\x04\x00\x01 \x08\x02%[1]dч\x02Понедельник\x02" +
	"Вторник\x02Среда\x02Четверг\x02Пятница\x02Суббота\x02Воскресенье"

	// Total table size 12089 bytes (11KiB); checksum: 7D3BA4A7
